# GROUP
@host=http://localhost:4000/api
@userId=6762366230adcfd63bd94de6
@groupId=67612a0e50d0f4d1caad6edc

### GET 
GET {{host}}/groups

### CREATE
POST {{host}}/groups/users/{{userId}}
Content-Type: application/json

{
  "name": "Nhóm 2"
}

### ADD USER IN GROUP
PATCH {{host}}/groups/{{groupId}}/users/676044b9cdb45183c1324d13

### DELETE USER IN GROUP
DELETE  {{host}}/groups/{{groupId}}/users/676044b9cdb45183c1324d13
